### ISSUE TITLE
Consider adding info on how to install the snap from the Ubuntu Store

### ISSUE THREAD

**Issue by frederickjh** [ralight/usb-reset#1]
Hi!
Thanks for your work on this. I see that you made this into a snap and that it is available in the Ubuntu Store and should be installable on Ubuntu 16.04. Earlier versions and other Linux distros may / will need to [install snapd](https://snapcraft.io/docs/core/install) first. Consider adding a link to usb-reset in the Ubuntu Store in the README.md.
[usb-reset in the Ubuntu Store](https://uappexplorer.com/snap/ubuntu/usb-reset)
Thanks!
Frederick

**Comment by ralight** [comment]
Thanks for the comments, I've now updated the readme with a few more details. There will be a new version on the store shortly.
