### ISSUE TITLE
F1-F12 keys don't work after reset

### ISSUE THREAD

**Issue by cpouldev** [ralight/usb-reset#4]
Thank you for this little gem.

After a usb keyboard reset, the F keys don't work anymore. I tried `xev` but it didn't show any results, they're like dead. Keyboard is fully functional again if I plug it out and then plug in it again. Mouse doesn't work at all, it needs re plugging too. 

Any thoughts? I'm using Arch and my kb/mouse is Logitech

**Comment by ralight** [comment]
Not the foggiest. All this does is send a reset request, so down to the device to re-enumerate and work properly afterwards.

**Comment by cpouldev** [comment]
It looks like its a logitech specific thing because of their hardware. Other brands look ok. 

Closing
